-- ================================================
-- ZOMATO FOOD DELIVERY SQL ANALYSIS
-- Business Questions
-- ================================================

-- Q1. Top 5 cities with the most restaurants
SELECT city, COUNT(r_id) AS total_restaurants
FROM restaurants
GROUP BY city
ORDER BY total_restaurants DESC
LIMIT 5;

-- Q2. Top 5 most expensive restaurants
SELECT name, city, cost 
FROM restaurants
WHERE cost IS NOT NULL
AND cost < 10000
ORDER BY cost DESC 
LIMIT 5;

-- Q3. Most loyal customers by number of orders
SELECT users.name, COUNT(*) AS total_orders
FROM orders
JOIN users ON orders.user_id = users.user_id
GROUP BY users.name
ORDER BY total_orders DESC
LIMIT 5;

-- Q4. Most popular restaurants by order count
SELECT restaurants.name, restaurants.city, COUNT(*) AS total_orders
FROM orders
JOIN restaurants ON orders.r_id = restaurants.r_id
GROUP BY restaurants.name, restaurants.city
ORDER BY total_orders DESC
LIMIT 5;

-- Q5. Revenue generated by each city
SELECT restaurants.city, SUM(orders.sales_amount) AS total_revenue
FROM orders
JOIN restaurants ON orders.r_id = restaurants.r_id
GROUP BY restaurants.city
ORDER BY total_revenue DESC
LIMIT 10;

-- Q6. Most popular cuisine by number of orders
SELECT restaurants.cuisine, COUNT(*) AS total_orders
FROM orders
JOIN restaurants ON orders.r_id = restaurants.r_id
GROUP BY restaurants.cuisine
ORDER BY total_orders DESC
LIMIT 10;

-- Q7. Veg vs Non-veg order distribution
SELECT food.veg_or_non_veg, COUNT(*) AS total_orders
FROM orders
JOIN menu ON orders.r_id = menu.r_id
JOIN food ON menu.f_id = food.f_id
GROUP BY food.veg_or_non_veg
ORDER BY total_orders DESC;

-- Q8. Peak ordering months
SELECT EXTRACT(MONTH FROM order_date) AS month, 
       COUNT(*) AS total_orders
FROM orders
GROUP BY month
ORDER BY total_orders DESC
LIMIT 12;

-- Q9. Average order value by customer occupation
SELECT users.occupation, 
       ROUND(AVG(orders.sales_amount), 2) AS avg_order_value
FROM users
JOIN orders ON users.user_id = orders.user_id
GROUP BY users.occupation
ORDER BY avg_order_value DESC;

-- Q10. Top restaurant in each city by number of orders
WITH restaurant_orders AS (
    SELECT restaurants.name, 
           restaurants.city, 
           COUNT(*) AS total_orders
    FROM orders
    JOIN restaurants ON orders.r_id = restaurants.r_id
    GROUP BY restaurants.name, restaurants.city
)
SELECT name, city, total_orders,
       RANK() OVER (PARTITION BY city ORDER BY total_orders DESC) AS rank
FROM restaurant_orders
WHERE rank = 1
ORDER BY total_orders DESC
LIMIT 10;