-- ================================================
-- ZOMATO FOOD DELIVERY SQL ANALYSIS
-- Business Questions
-- ================================================

-- Q1. Top 5 cities with the most restaurants
SELECT city, COUNT(r_id) AS total_restaurants
FROM restaurants
GROUP BY city
ORDER BY total_restaurants DESC
LIMIT 5;

-- Q2. Top 5 most expensive restaurants
SELECT name, city, cost 
FROM restaurants
WHERE cost IS NOT NULL
AND cost < 10000
ORDER BY cost DESC 
LIMIT 5;

-- Q3. Most loyal customers by number of orders
SELECT users.name, COUNT(*) AS total_orders
FROM orders
JOIN users ON orders.user_id = users.user_id
GROUP BY users.name
ORDER BY total_orders DESC
LIMIT 5;

-- Q4. Most popular restaurants by order count
SELECT restaurants.name, restaurants.city, COUNT(*) AS total_orders
FROM orders
JOIN restaurants ON orders.r_id = restaurants.r_id
GROUP BY restaurants.name, restaurants.city
ORDER BY total_orders DESC
LIMIT 5;

-- Q5. Revenue generated by each city
SELECT rest