# Zomato Food Delivery SQL Analysis

## Project Overview
Analysed 1.9 million+ records across 5 tables (users, restaurants, orders, food, menu) covering 821 cities across India using PostgreSQL and pgAdmin, spanning October 2017 to June 2020. The goal was to understand customer behaviour, restaurant performance, and revenue trends through SQL queries.

## Dataset
- Source: Kaggle
- Time Period: October 2017 to June 2020
- Total Records: 1.9 million+ across 5 tables

## Tables
| Table | Key Columns |
|---|---|
| users | user_id, name, age, gender, occupation, monthly_income |
| restaurants | r_id, name, city, rating, cost, cuisine |
| orders | order_id, user_id, r_id, order_date, sales_amount |
| food | f_id, item, veg_or_non_veg |
| menu | menu_id, r_id, f_id, cuisine, price |

## Tools Used
- PostgreSQL (Database)
- pgAdmin 4 (GUI)
- psql (Command line import)
- PyCharm (Data cleaning script)

## Data Cleaning
- Removed 1,617 NULL r_id rows from orders table
- Removed 1,611 rows with invalid sales_amount (0 or -1)
- Fixed rating column in restaurants — replaced '--' with NULL for unrated restaurants
- Stripped ₹ symbol from cost column and converted to INTEGER
- Handled encoding issues (WIN1252, LATIN1) during CSV import
- Dropped unnamed index column generated by pandas during CSV export
- Removed foreign key constraints temporarily to handle messy data during import

## Business Questions
1. Top 5 cities with the most restaurants
2. Top 5 most expensive restaurants
3. Most loyal customers by number of orders
4. Most popular restaurants by order count
5. Revenue generated by each city
6. Most popular cuisine by number of orders
7. Veg vs Non-veg order distribution
8. Peak ordering months
9. Average order value by customer occupation
10. Top restaurant in each city by orders

## Key Findings
-## Key Findings
- Tirupati generates the highest revenue (₹4.25 crore) 
  despite not being a metro city
- November is the peak ordering month, likely due to 
  Diwali festive season
- 68% of orders are vegetarian vs 31% non-veg, 
  reflecting India's dietary preferences
- Average user age is 24.6 years — entirely Gen Z 
  and young millennials
- North Indian + Chinese is the most popular cuisine 
  combo with 6,409 orders
- Students spend the most per order (₹6,590) despite 
  having no income — likely group orders
- Zomato operates across 821 cities in India
- David Smith is the most loyal customer with 64 orders 
  over 2.5 years

## SQL Concepts Used
- DDL (CREATE TABLE, ALTER TABLE, DROP TABLE)
- Data Import (COPY, \copy)
- Data Cleaning (UPDATE, DELETE, REGEXP_REPLACE)
- Aggregations (COUNT, SUM, AVG, ROUND)
- GROUP BY and HAVING
- ORDER BY and LIMIT
- JOIN (2 table and 3 table)
- Subqueries
- CTEs (Common Table Expressions)
- Window Functions (RANK, PARTITION BY)
- Date Functions (EXTRACT, TO_CHAR)
- NULL handling (IS NULL, IS NOT NULL)